openapi: 3.0.3
info:
  title: コーディネーターユーザー管理API
  description: ユーザーアカウントの作成・更新・削除API（管理者専用）
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: ローカル開発環境

paths:
  /api/users:
    get:
      summary: ユーザー一覧取得
      description: すべてのユーザーを取得（管理者専用）
      operationId: listUsers
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: ユーザー一覧取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '401':
          description: 未認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 権限不足（管理者のみアクセス可能）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: ユーザー作成
      description: 新規ユーザーアカウントを作成（管理者専用）
      operationId: createUser
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - role
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                  pattern: ^[a-zA-Z0-9_]+$
                  example: john_doe
                password:
                  type: string
                  minLength: 8
                  example: secure123
                role:
                  type: string
                  enum: [admin, viewer]
                  example: viewer
      responses:
        '201':
          description: ユーザー作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: リクエストが不正（ユーザー名重複等）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 未認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 権限不足
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: ユーザーID

    put:
      summary: ユーザー更新
      description: ユーザー情報を更新（管理者専用）
      operationId: updateUser
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  minLength: 8
                  description: 新しいパスワード（省略可）
                  example: new_password123
                role:
                  type: string
                  enum: [admin, viewer]
                  description: 新しいロール（省略可）
                  example: admin
      responses:
        '200':
          description: ユーザー更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 未認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 権限不足
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: ユーザー削除
      description: ユーザーアカウントを削除（管理者専用）
      operationId: deleteUser
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: ユーザー削除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User deleted successfully
        '400':
          description: 削除不可（最後の管理者等）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: 未認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: 権限不足
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ユーザーが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - id
        - username
        - role
        - created_at
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        username:
          type: string
          example: john_doe
        role:
          type: string
          enum: [admin, viewer]
          example: viewer
        created_at:
          type: string
          format: date-time
          example: '2025-11-17T10:30:00Z'
        last_login:
          type: string
          format: date-time
          nullable: true
          example: '2025-11-17T15:45:00Z'

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: User not found
